### ISSUE TITLE
Courses folder config does not work

### ISSUE THREAD

**Issue by yagarea** [xiaoxiae/Lecture-Notes-Scripts#4]
I have set `courses_folder = "~/School/"` and it created `School` directory in scripts directory.

I get same result if I write relative path from script (`../../`)

**Comment by xiaoxiae** [comment]
It seems that there is a bug with how `os.walk` handles relative paths and I will fix that. However, the `school` script should only create a new directory when initializing a new year, which always happens relative to where you're executing the `school` command - does that not work?

**Comment by xiaoxiae** [comment]
Ah, ok, I understand that this behavior is confusing. I'll fix it to initialize based on `courses_folder` (and fix the relative path bug).
