### ISSUE TITLE
make info.yaml hidden file

### ISSUE THREAD

**Issue by yagarea** [xiaoxiae/Lecture-Notes-Scripts#7]
change file `info.yaml` to `.info.yaml` so it is considered hidden file and stop clutter course directory.

**Comment by xiaoxiae** [comment]
This could be done by renaming the `course_yaml` variable to `.info.yaml`. Do you think it should be default behavior?

**Comment by yagarea** [comment]
Making it hidden by default is good decision in my opinion. This is not file you will be interacting every often.

**Comment by xiaoxiae** [comment]
Fair enough, will change.

**Comment by xiaoxiae** [comment]
I made it so that if the `yaml` file is hidden, non-hidden variants will also be parsed (for backwards compatibility).
