### ISSUE TITLE
List of ignored courses (Ignore PE)

### ISSUE THREAD

**Issue by yagarea** [xiaoxiae/Lecture-Notes-Scripts#9]
Make list of courses which will be ignored in init.
For example: `Tělesná výchova III (TVI)`

**Comment by xiaoxiae** [comment]
I don't understand, ignored in init means that it will not be parsed at all.

**Comment by yagarea** [comment]
> I don't understand, ignored in init means that it will not be parsed at all.

Yes

**Comment by xiaoxiae** [comment]
It seems like this would be more inconvenient than just removing the line in the CSV or the folder itself, no?

**Comment by xiaoxiae** [comment]
Closing for now, feel free to reopen later.
